ca=int(input('Digite a medida do cateto adjascente: '))
ma=(ca**2)
co=int(input('Digite o cateto oposto: '))
mo=(co**2)
s=(ma+mo)
print('A hipotenusa do triangulo retangulo é \033[1;30m{}\033[m'.format(s))